### ISSUE TITLE
pretrained model weight

### ISSUE THREAD

**Issue by wytszhuzhu** [aimagelab/camel#5]
it's a nice work. could you update the pretrained model weight in the google drive(Too many users have recently viewed or downloaded this file. Please try accessing this file again later. If the file you are trying to access is particularly large or has been shared with many people, you may have to wait up to 24 hours before viewing or downloading the file. If you are still unable to access your files after 24 hours, please contact your domain administrator.)

**Comment by wytszhuzhu** [comment]
the annotations.zip has the same problem.

**Comment by manuelebarraco** [comment]
Hey! It is a Google Drive problem, sometimes it blocks the download but when this happens it should work again after a few hours.
