### ISSUE TITLE
SCST  strategies

### ISSUE THREAD

**Issue by yuge2648474909** [aimagelab/camel#9]
Can you tell us about training different SCST strategies? I don't know how to operate it

**Comment by manuelebarraco** [comment]
Hi! We didn't try different SCST strategies apart from the one described in section IIIA in the paper. The SCST part is [from L156 to L167 in train.py](https://github.com/aimagelab/camel/blob/main/train.py#L156).

**Comment by yuge2648474909** [comment]
The problem has been solved, it was my mistake, thank you very much
